# Generated by Django 3.1.5 on 2021-01-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todob', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_done',
        ),
    ]
