# Generated by Django 3.1.5 on 2021-01-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todob', '0002_remove_task_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
