# Generated by Django 3.1.5 on 2021-01-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todob', '0003_auto_20210125_0834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
