# Generated by Django 3.1.5 on 2021-01-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todob', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
