# Generated by Django 3.1.5 on 2021-01-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todob', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
